package com.live.rrutt.ui;

public class YesNoDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = -5617762425406392598L;

	private boolean yes = true;

	private String msg = "";

	/** Creates new form OkDialog */
	public YesNoDialog(java.awt.Frame parent, boolean modal, String msg) {
		super(parent, modal);
		this.msg = msg;
		initComponents();
		setLocationRelativeTo(null); // Center on screen.
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() { // GEN-BEGIN:initComponents
		jLabel1 = new javax.swing.JLabel();
		bYes = new javax.swing.JButton();
		bNo = new javax.swing.JButton();

		getContentPane().setLayout(new java.awt.FlowLayout());

		setTitle("Hurricane");
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Arial", 0, 12));
		jLabel1.setText(msg);
		jLabel1.setMinimumSize(new java.awt.Dimension(150, 15));
		jLabel1.setPreferredSize(new java.awt.Dimension(150, 15));
		getContentPane().add(jLabel1);

		bYes.setFont(new java.awt.Font("Arial", 0, 10));
		bYes.setText("Yes");
		bYes.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bYesActionPerformed(evt);
			}
		});

		getContentPane().add(bYes);

		bNo.setFont(new java.awt.Font("Arial", 0, 10));
		bNo.setText("No");
		bNo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bNoActionPerformed(evt);
			}
		});

		getContentPane().add(bNo);

		pack();
	} // GEN-END:initComponents

	private void bNoActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_bNoActionPerformed
		yes = false;
		dispose();
	} // GEN-LAST:event_bNoActionPerformed

	private void bYesActionPerformed(java.awt.event.ActionEvent evt) { // GEN-FIRST:event_bYesActionPerformed
		yes = true;
		dispose();
	} // GEN-LAST:event_bYesActionPerformed

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) { // GEN-FIRST:event_closeDialog
		setVisible(false);
		dispose();
	} // GEN-LAST:event_closeDialog

	public boolean yes() {
		return this.yes;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;

	private javax.swing.JButton bYes;

	private javax.swing.JButton bNo;
	// End of variables declaration//GEN-END:variables
}
